// Generated by Manifold Setup Wizard
// Kadena Chainweb EVM Configuration - 9/28/2025, 8:09:10 AM

export const manifoldConfig = {
  useCase: 'defi',
  useCaseName: 'DeFi Protocol',
  selectedChains: [20,21,22],
  selectedFunctions: ["crossChainTransfer","multiChainDeploy","getChainBalances","addLiquidityMultiChain","executeArbitrage","crossChainYieldFarm","multiChainLending"],
  functionSelectionMode: 'recommended',
  chainCount: 3,
  generatedAt: '2025-09-28T02:39:10.194Z',
  isDefault: false
}

export default manifoldConfig